web:
 build: .
 links:
  - "db:postgres"
 volumes:
  - ".:/app:rw"
  - "./data:/data:rw"
 command: start web
 env_file: .env-local
 expose:
  - "80"

db:
 image: postgres:9.4.24
 volumes:
  - ".:/app:rw"
