web:
 build: .
 links:
  - "db:postgres"
 ports:
  - "80:80"
 volumes:
  - ".:/app:rw"
  - "./data:/data:rw"
 command: start web
 env_file: .env-local

db:
 image: postgres:9.4
 volumes:
  - ".:/app:rw"
