web:
 build: .
 links:
  - "db:postgres"
 ports:
  - "80:80"
  - "443:443"
 volumes:
  - ".:/app:rw"
  - "./data:/data:rw"
  - "/etc/certbot/:/etc/letsencrypt"
 command: start web
 env_file: .env-local

db:
 image: postgres:9.4
 volumes:
  - ".:/app:rw"
